version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: kanan111"
      MYSQL_DATABASE: GoKapture
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=kanan111"
      - DB_NAME=GoKapture

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

